<?xml version="1.0" encoding="UTF-8"?>

 <!--От зададената dtd граматика можем да установим, че корен-елементът на XML документа ще бъде Course_Catalog.
    Направих един елемент Department (може да има един или повече). Той съдържа заглавие, катедра и 1 курс(може да има и повече). 
    В катедрата има професор с име, презиме и фамилия.Курсът има номер, заглавие, описание, инструктури и предпоставки. Може да има 
    и Enrollment, да няма описание и предпоставки. За инструктури имах опция да избера между 1 лектор и 0 или повече профецори
    или 1 или повече профецори и 0 или повече лектори. Избрах да имам един лектор и един професор. -->

<!DOCTYPE Course_Catalog [
    <!ELEMENT Chair (Professor)>
    <!ELEMENT Title (#PCDATA)>
    <!ELEMENT Course (Title, Description?, Instructors, Prerequisites?)>
    <!ATTLIST Course
    Number (CS106A | CS106B | CS107 | CS109 | CS124 | CS143 | CS145 | CS221 | CS228 | CS229 | EE108A | EE108B | LING180) #REQUIRED
    Enrollment (1070 | 110 | 130 | 180 | 280 | 320 | 500 | 60 | 620 | 90) #IMPLIED
    >
    <!ELEMENT Prereq (#PCDATA)>
    <!ELEMENT Lecturer (First_Name, Middle_Initial?, Last_Name)>
    <!ELEMENT Last_Name (#PCDATA)>
    <!ELEMENT Professor (First_Name, Middle_Initial?, Last_Name)>
    <!ELEMENT Department (Title, Chair, Course+)>
    <!ATTLIST Department Code (CS | EE | LING) #REQUIRED>
    <!ELEMENT First_Name (#PCDATA)>
    <!ELEMENT Description (#PCDATA)>
    <!ELEMENT Instructors ((Lecturer, Professor*) | (Professor+, Lecturer?))>
    <!ELEMENT Prerequisites (Prereq+)>
    <!ELEMENT Course_Catalog (Department+)>
    <!ELEMENT Middle_Initial (#PCDATA)>
    ]>
<Course_Catalog>
    <Department Code="CS">
        <Title></Title>
        <Chair>
            <Professor>
                <First_Name></First_Name>
                <Middle_Initial></Middle_Initial>
                <Last_Name></Last_Name>
            </Professor>
        </Chair>
        <Course Number="CS106B">
            <Title></Title>
            <Description></Description>
            <Instructors>
                <Lecturer>
                    <First_Name></First_Name>
                    <Middle_Initial></Middle_Initial>
                    <Last_Name></Last_Name>
                </Lecturer>
                <Professor>
                    <First_Name></First_Name>
                    <Middle_Initial></Middle_Initial>
                    <Last_Name></Last_Name>
                </Professor>
            </Instructors>
            <Prerequisites>
                <Prereq></Prereq>
            </Prerequisites>
        </Course>
    </Department>
</Course_Catalog>