=== iskrabozhkova/XML/2.Module/task6.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!--Това е dtd файла. Първо пишем root елемента, а след това описваме и неговите под-елементи. Ако има атрибути, също ги описваме.-->

<!ELEMENT games (game)>
<!ELEMENT game (home-team, ex-team, scores, yellows, reds)>
<!ATTLIST game score CDATA #REQUIRED>
<!ATTLIST score me CDATA #REQUIRED>
<!ATTLIST score type (penalty|num) #IMPLIED>
<!ELEMENT home-team (#PCDATA)>
<!ELEMENT ex-team (#PCDATA)>
<!--може да няма отбелязан резултат или да има повече от един-->
<!ELEMENT scores (score)*>
<!--ако няма отбелязан резултат, то играчите са 0, но ако има играчът е един-->
<!ELEMENT score (player)*>
<!ELEMENT player (#PCDATA) >
<!--може да няма играчи, получили жълт или червен картон, но може и да има няколко-->
<!ELEMENT yellows (player)* >
<!ELEMENT reds (player)* >

=== iskrabozhkova/XML/2.Module/task6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Правим xml файл, който да бъде валиден и да изпълнява изброените в условието изисквания. -->

<!DOCTYPE games SYSTEM "task6.dtd">
<games>
    <game score="1-1">
           <home-team>Roma</home-team>
           <ex-team>Lazio</ex-team>
           <scores>
              <score me="15">
                <player>Klose</player>
              </score>
              <score me="85" type="penalty">
                <player>Tox</player>
              </score>
           </scores>
        <yellows>
           <player>Tox</player>
           <player>Hernanes</player>
        </yellows>
        <reds>
           <player>Kjaer</player>
        </reds>
    </game>
</games>
