=== iskrabozhkova/XML/3. Module/task1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--TO DO: CDATA какъв тип е? -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
   <xs:element name="collection">
    <xs:complexType>
        <xs:sequence>
          <xs:element name="description"/>
          <xs:element name="recipe" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                  <xs:element name="title" type="xs:string"></xs:element>

                  <xs:element name="ingerdient" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="preparation" minOccurs="0" maxOccurs="1">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>

                      </xs:sequence>
                      <xs:attribute name="name" use="required"/>
                      <xs:attribute name="amount"/>
                      <xs:attribute name="unit"/>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="preparation">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                  <xs:element name="nutrition">
                      <xs:complexType>
                        <xs:attribute name="protein" use="required"/>
                        <xs:attribute name="carbohydrates" use="required"/>
                        <xs:attribute name="fat" use="required"/>
                        <xs:attribute name="calories" use="required"/>
                        <xs:attribute name="alcohol"/>
                      </xs:complexType>
                  </xs:element>
              </xs:sequence>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>




<!--
@<!ELEMENT collection (description,recipe*)>
@<!ELEMENT description ANY>
@<!ELEMENT recipe (title,ingredient*,preparation,comment?,nutrition)>
@<!ELEMENT title (#PCDATA)>
@<!ELEMENT ingredient (preparation?)>
@<!ATTLIST ingredient name CDATA #REQUIRED
                     amount CDATA #IMPLIED
                     unit CDATA #IMPLIED>
@<!ELEMENT preparation (step*)>
@<!ELEMENT step (#PCDATA)>
@<!ELEMENT comment (#PCDATA)>
@<!ELEMENT nutrition EMPTY>
<!ATTLIST nutrition protein CDATA #REQUIRED
                    carbohydrates CDATA #REQUIRED
                    fat CDATA #REQUIRED
                    calories CDATA #REQUIRED
                    alcohol CDATA #IMPLIED>
-->

=== iskrabozhkova/XML/3. Module/task1.xml
<?xml version="1.0" encoding="UTF-8"?>

  <!--Създавам XML документ, за да валидирам задачата. -->
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="task1.xsd">
    <description>Description</description>
    <recipe>
        <title>Title</title>
        <ingredient name="ingredient">
            <preparation>
                <step>First step</step>
                <step>Second step</step>
            </preparation>
        </ingredient>
        <preparation>
            <step>First step</step>
            <step>Second step</step>
        </preparation>
        <comment>Comment</comment>
        <nutrition protein="" carbohydrates="" fat="" calories="" />
    </recipe>
</collection>
